/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-12-07 10:21:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ApplicationDao.CarModelDao;
import ApplicationDao.CarTypeDao;
import java.util.List;
import model.CarType;
import model.CarModel;

public final class createModel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\r\n");
      out.write("<title>Add Cars</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"hello bum!\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		//---------------------Controller 
		CarModelDao carModelDao = new CarModelDao();
		String modelName = request.getParameter("modelName");
		//---------Get values to insert data
		String modelCount = request.getParameter("modelCount");
		String carType = request.getParameter("carType");
		String action = request.getParameter("action");
		String idStr = request.getParameter("id");

		System.out.println(modelCount);
		System.out.println(carType);
		System.out.println(action);
		System.out.println(idStr);
		CarModel carmodel = new CarModel();
		// CREATE A MODEL
		if ("create".equals(action) && !carType.equals("0")) {
			int count = Integer.parseInt(modelCount);
			carmodel = new CarModel(carType, modelName, count);
			carModelDao.insertCarModel(carmodel);
		}
		// DELETE A MODEL
		if ("delete".equals(action) && !idStr.equals("0")
				&& !idStr.equals("null")) {
			int id = Integer.parseInt(idStr);
			carModelDao.removeCarModel(id);
		}
		// SELECT A MODEL
		if ("select".equals(action) && !idStr.equals("0")
				&& !idStr.equals("null")) {
			int id = Integer.parseInt(idStr);
			carmodel = carModelDao.getModelById(id);
			request.setAttribute("carType", carmodel.getCarTypeCode());

		}
		// Update A Model
		if ("update".equals(action) && !idStr.equals("0")
				&& !idStr.equals("null") && !carType.equals("0")) {
			int id = Integer.parseInt(idStr);
			int count = Integer.parseInt(modelCount);
			carmodel = new CarModel(carType, modelName, count);
			carModelDao.updateCarModel(id, carmodel);
			request.setAttribute("carType", carmodel.getCarTypeCode());

		}

		List<CarModel> lstCarModels = carModelDao.getAllCarModel();
	
      out.write("\r\n");
      out.write("\t<form action=\"createModel.jsp\">\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t<!--  CAR TYPE DROP DOWN -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label> Select a Car Type </label></td>\r\n");
      out.write("\t\t\t\t<td><select name=\"carType\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected>- select -</option>\r\n");
      out.write("\t\t\t\t\t\t");

							CarTypeDao carTypeDao = new CarTypeDao();
							List<CarType> lstCarType = carTypeDao.getAllCarTypes();
							for (CarType c : lstCarType) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(c.getCarTypeCode());
      out.write('"');
      out.write('>');
      out.print(c.getCarTypeName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<td><label id=\"error\" style=\"visibility: hidden;\">Please\r\n");
      out.write("\t\t\t\t\t\tselect Car Type</label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- CAR MODEL NAME AND COUNT FIELDS -->\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(carmodel.getModelId());
      out.write("\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" class=\"form-control\" name=\"modelName\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(carmodel.getModelName());
      out.write("\" placeholder=\"Enter Car Model\"></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" class=\"form-control\" name=\"modelCount\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(carmodel.getCount());
      out.write("\" placeholder=\"Enter Car Count\"></td>\r\n");
      out.write("\t\t\t\t<td><button class=\"btn btn-success\" name=\"action\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"create\">Add</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" name=\"action\" value=\"update\">Update</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				for (CarModel c : lstCarModels) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(c.getModelName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(c.getCount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><a class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\thref=\"createModel.jsp?action=delete&id=");
      out.print(c.getModelId());
      out.write("\">Delete</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-warning\"\r\n");
      out.write("\t\t\t\t\thref=\"createModel.jsp?action=select&id=");
      out.print(c.getModelId());
      out.write("\">Select</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
