/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-12-07 12:26:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ApplicationDao.CarTypeDao;
import ApplicationDao.CarModelDao;
import ApplicationDao.RentalDao;
import java.util.ArrayList;
import java.util.List;
import model.CarType;
import model.CarModel;
import model.Rental;

public final class ListOfCarRental_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\r\n");
      out.write("<title>List Of Car Rental</title>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" #slide-images{\r\n");
      out.write("height: 142px;\r\n");
      out.write("margin-bottom: 5px;\r\n");
      out.write("display: block;}\r\n");
      out.write("\r\n");
      out.write(" #resultDetails{\r\n");
      out.write(" border: 1px solid #e1e1e1;\r\n");
      out.write("display: block;\r\n");
      out.write("font-size: 12px;\r\n");
      out.write("height: 114px;\r\n");
      out.write("margin: 0;\r\n");
      out.write("padding: 7px 0 14px 18px;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		CarTypeDao carTypeDao = new CarTypeDao();
		List<CarType> lstCarType = carTypeDao.getAllCarTypes();
		RentalDao rentalDao = new RentalDao();
	
      out.write("\r\n");
      out.write("\t<table class=\"table\">\r\n");
      out.write("\t\t");

			for (CarType c : lstCarType) {  
      out.write("\r\n");
      out.write("\t\t<tr class=\"resultWrapper\">\r\n");
      out.write("\t\t<div class=\"resultDetails\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<td><ul> ");
      out.print( c.getCarTypeName() );
      out.write("</ul>\r\n");
      out.write("\t\t\t\t<ul> <img id =\"test\" src=\"images/");
      out.print( c.getCarTypeName());
      out.write(".png\"> </ul></td> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<ul><label> Lowest fare </label>\t</ul>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

							List<Rental> lstrental = new ArrayList<Rental>();
							lstrental=(List<Rental>)rentalDao.getAllRental();
							List<Rental> lstselectedrentals = new ArrayList<Rental>();
							for (Rental r : lstrental) {
								if(r.getCarTypeCode().equals(c.getCarTypeCode())){
									lstselectedrentals.add(r);									
								}								
							}		
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<ul>\t");
      out.print( lstselectedrentals.get(0).getSubTotal());
      out.write(" </ul>\r\n");
      out.write("\t\t\t\t\t<ul>\t");
      out.print(lstselectedrentals.get(0).getTotalPrice());
      out.write("</ul>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td><ul><label> Select a Model </label></ul>\r\n");
      out.write("\t\t\t<ul><select name=\"carType\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected>- select -</option>\r\n");
      out.write("\t\t\t\t\t\t");

							CarModelDao modelDao = new CarModelDao();
							List<CarModel> lstCarModel = modelDao.getAllCarModel();
							List<CarModel> lstselectedModels = new ArrayList<CarModel>();
							for (CarModel cm : lstCarModel) {
								if(cm.getCarTypeCode().equals(c.getCarTypeCode())){
									lstselectedModels.add(cm);									
								}								
							}							
							
							for (CarModel scm : lstselectedModels) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(scm.getModelId());
      out.write('"');
      out.write('>');
      out.print(scm.getModelName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t</select></ul></td>\r\n");
      out.write("\t\t\t<td><ul> ");
      out.print( c.getSeatingInfo() );
      out.write("</ul>\r\n");
      out.write("\t\t\t<ul><button id=\"continue\" class=\"btn btn-success\" name=\"action\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"continue\">Continue</button></ul></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 }
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
